### PR TITLE
French translation added

### PR DESCRIPTION
**Pull request by ghost**
Thanks you for the .pot file!
Here is a proposal of translation in French.
Have you ever considered to host the translations in [Launchpad](https://wiki.ubuntu.com/Translations/LpProjectConfiguration), this way the translations could be more easily reviewed by Ubuntu Translators?

### CODE REVIEW

**Comment by perryhelion** [comment]
Thanks for the French Translation - didn't expect it all to be done so quickly but that's excellent! Very much appreciated!

My only worry is for the translation of 'Current Hex' (line 108) - the 'popover' is not the full width of the screen and so 'Couleur hexadécimale actuelle' might not display correctly - I could set wrapMode to Text.WordWrap so it doesn't get cut off or try to write outside the popover horizontally, but then it might have a similar problem vertically. Is it possible to translate it as 'Hexadécimale actuelle' and for it to still make sense?

I've looked at Launchpad and do have plans to use it in the near future but might not get round to it until after the New Year. GitHub made it very easy just to put up the main qml file but I'm not really using it properly - the last time I 'updated' the project, I just deleted what was there and uploaded the new version - so I'll attempt to get to grips with the basics on GitHub and then hopefully make proper use of Launchpad and bzr once I've got a better understanding of what I'm doing :)

Thanks again for all your great work,

Kindest regards,
P Helion

**Comment by ghost** [comment]
"Couleur hex. actuelle" should be short and understandable enough

**Comment by perryhelion** [comment]
I've made another branch, called **Cleaned Up & With Translations**, which has all the files more properly arranged & your French translation has been added into the proper **po** folder there. 

I'll close this pull request in a couple of days but thanks again for letting me know that the application couldn't be translated without the .pot file - I've had fun testing the app using the French locale :)

Kindest regards,
P Helion

**Comment by perryhelion** [comment]
Just a last quick message - forgot that if I reply on Github it doesn't let
you know directly - the details are in the pull request messages but thanks
for all your great work and both Hex Explorer and sTOnSCipAP are now up on
Launchpad, so it should make it easier for the Translation Teams to find
them now.

Kindest regards,
P Helion

**Comment by ghost** [comment]
Thank you very much!
Your projects are now on Launchpad but translations are not accessible yet.
You need to go [here](https://translations.launchpad.net/stonscipap/+configure-translations) and [here](https://translations.launchpad.net/hexexplorer/+configure-translations).
More information are available in this [wiki](https://wiki.ubuntu.com/Translations/LpProjectConfiguration).

**Comment by perryhelion** [comment]
Ah, darn it. Thought I'd set it up with 'drive by' translations enabled but
I should get it sorted out in a day or two - thanks for letting me know!

Kindest regards,
P Helion

**Comment by ghost** [comment]
Hello, are you encountering troubles to activate the translations in Launchpad?
Let me know if I can help.

**Comment by perryhelion** [comment]
Hello Anne017, thanks for your note - I think I've set up each project to
be translated by Launchpad Translators with Open permissions, and if I
visit Launchpad without signing in, each project has a 'Help translate ->'
button enabled.

What I haven't done though (which I only checked up on after I got your
message), is to take their advice to "...send an initial message to the
Launchpad Translators Team and let them know about your project. "

So I think they're set up for translation, it's just that nobody knows
about the projects yet :)

I'm in the process of making a couple of changes to sTOnSCipAP, which will
add some more text to the translation files (basically just: "Stone blunts
Scissors", "Scissors cut Paper", "Paper covers Stone"), so I was going to
wait until I've updated sTOnSCipAP before contacting them about that.

I've got Hex Explorer though, and I don't think I'll be adding anymore text
to RockScissorsPaperLizardSpock, so I'll try and contact them in the next
week or so and see if I'm on the right track.

As far as I can tell, I would just send a message to the Launchpad
Translators team to tell them about the projects, but any advice you have
to offer about the best way to go about that would be welcomed.

kindest regards,
P Helion

**Pull request closed without merging**
